# Generated by Django 4.0.4 on 2022-05-05 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=6, null=True, verbose_name='Owner Name')),
                ('state', models.CharField(default='Kerala', max_length=20, verbose_name='State')),
                ('district', models.CharField(choices=[('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thrissur', 'Thrissur'), ('Wayanad', 'Wayanad')], max_length=20, verbose_name='District')),
                ('landmark', models.CharField(blank=True, max_length=50, verbose_name='Landmark')),
                ('retailer_type', models.CharField(choices=[('Hospital Pharmacy', 'Hospital Pharmacy'), ('Medical Store', 'Medical Store'), ('Chain Pharmacy', 'Chain Pharmacy'), ('FMCG', 'FMCG'), ('Others', 'Others')], max_length=20, verbose_name='Retailer Type')),
                ('dl_number1', models.CharField(max_length=20, verbose_name='DL Number2')),
                ('dl_number2', models.CharField(max_length=20, verbose_name='DL Number2')),
                ('dl_expiry_date', models.DateField(verbose_name='DL Expiry Date')),
                ('gst', models.CharField(max_length=20, verbose_name='GST')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('ref_code', models.CharField(max_length=20, null=True, verbose_name='Reference Code')),
                ('retailer_name', models.CharField(max_length=20, verbose_name='Retailer Name')),
                ('joined_date', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_code', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('unit_quantity', models.IntegerField()),
                ('MRP', models.FloatField()),
                ('Rate', models.FloatField()),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdayaApp.category')),
            ],
        ),
    ]
