# Generated by Django 4.0.4 on 2022-05-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdayaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pack',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
