# Generated by Django 4.0.4 on 2022-05-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdayaApp', '0002_product_brand_name_product_company_name_product_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='gst18',
            field=models.BooleanField(default=False),
        ),
    ]
