# Generated by Django 4.0.4 on 2022-05-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_order_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
